# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtZ8nNh9szwjcDRUctiwj5yjd4Swl_Vw
"""



import streamlit as st
import pickle
import re
import PyPDF2

# Load files
model = pickle.load(open("resume_model.pkl", "rb"))
tfidf = pickle.load(open("tfidf_vectorizer.pkl", "rb"))
le = pickle.load(open("label_encoder.pkl", "rb"))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

def extract_text_from_pdf(file):
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text

st.set_page_config(page_title="Resume Screening System", page_icon="📄")
st.title("📄 Resume Screening System")
st.write("Upload your resume to predict the suitable job role.")

uploaded_file = st.file_uploader("Upload Resume (PDF or TXT)", type=["pdf", "txt"])

if uploaded_file:
    if uploaded_file.type == "application/pdf":
        resume_text = extract_text_from_pdf(uploaded_file)
    else:
        resume_text = uploaded_file.read().decode("utf-8")

    cleaned = clean_text(resume_text)
    vectorized = tfidf.transform([cleaned])
    prediction = model.predict(vectorized)
    category = le.inverse_transform(prediction)

    st.success(f"✅ Predicted Job Role: **{category[0]}**")
